services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: premium-polymers-app
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001"

  postgres:
    image: postgres:16
    container_name: premium-polymers-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: premium_polymers
      POSTGRES_USER: premium_polymers
      POSTGRES_PASSWORD: 9634609988Aa
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U premium_polymers -d premium_polymers" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - premium-polymers-postgres:/var/lib/postgresql/data

volumes:
  premium-polymers-postgres:
